blank_issues_enabled: false
contact_links:
  - name: File an issue
    url: "https://github.com/veeragoni/cdktf-provider-oci/issues/new/choose"
    about: Report problems or request features for this provider directly in this repository.
